export type CEFRLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export interface VocabItem {
  word: string;
  ru: string;
  uz: string;
  definition: string;
  pronunciation?: string;
  example?: string;
}

export const CEFR_PACKS: Record<CEFRLevel, VocabItem[]> = {
  A1: [
    { word: 'cat', ru: 'кот', uz: 'mushuk', definition: 'A small domesticated carnivorous mammal', example: 'The cat is sleeping on the sofa.' },
    { word: 'dog', ru: 'собака', uz: 'it', definition: 'A domesticated carnivorous mammal', example: 'The dog runs in the park.' },
    { word: 'book', ru: 'книга', uz: 'kitob', definition: 'A written or printed work', example: 'I am reading a book.' },
    { word: 'house', ru: 'дом', uz: 'uy', definition: 'A building for human habitation', example: 'Their house is big.' },
    { word: 'water', ru: 'вода', uz: 'suv', definition: 'A transparent fluid essential for life', example: 'Drink some water.' },
    { word: 'food', ru: 'еда', uz: 'ovqat', definition: 'Any nutritious substance that people eat or drink', example: 'The food tastes good.' },
    { word: 'school', ru: 'школа', uz: 'maktab', definition: 'An institution for educating children', example: 'She goes to school every day.' },
    { word: 'teacher', ru: 'учитель', uz: 'oʻqituvchi', definition: 'A person who teaches', example: 'The teacher explains the lesson.' },
    { word: 'student', ru: 'студент', uz: 'talaba', definition: 'A person who is studying', example: 'The student studies English.' },
    { word: 'family', ru: 'семья', uz: 'oila', definition: 'A group of related people living together', example: 'My family is small.' },
    { word: 'city', ru: 'город', uz: 'shahar', definition: 'A large town', example: 'The city is busy.' },
    { word: 'car', ru: 'машина', uz: 'mashina', definition: 'A road vehicle with an engine', example: 'He drives a new car.' },
    { word: 'friend', ru: 'друг', uz: 'doʻst', definition: 'A person whom one knows and likes', example: 'My friend helps me.' },
    { word: 'work', ru: 'работа', uz: 'ish', definition: 'Activity involving mental or physical effort', example: 'I work in an office.' },
    { word: 'shop', ru: 'магазин', uz: 'doʻkon', definition: 'A place where goods are sold', example: 'They shop at the market.' },
    { word: 'morning', ru: 'утро', uz: 'ertalab', definition: 'The early part of the day', example: 'Good morning!' },
    { word: 'night', ru: 'ночь', uz: 'tun', definition: 'The time of darkness each day', example: 'Good night!' },
    { word: 'coffee', ru: 'кофе', uz: 'qahva', definition: 'A drink made from roasted coffee beans', example: 'I like coffee.' },
    { word: 'bread', ru: 'хлеб', uz: 'non', definition: 'Food made of flour and water, baked', example: 'She buys bread.' },
    { word: 'milk', ru: 'молоко', uz: 'sut', definition: 'A white liquid produced by mammals', example: 'Milk is in the fridge.' },
  ],
  A2: [
    { word: 'apartment', ru: 'квартира', uz: 'kvartira', definition: 'A set of rooms forming a residence', example: 'They rent a small apartment.' },
    { word: 'neighbor', ru: 'сосед', uz: 'qoʻshni', definition: 'A person living near', example: 'Our neighbor is friendly.' },
    { word: 'vacation', ru: 'отпуск', uz: 'taʼtil', definition: 'An extended period of leisure and recreation', example: 'We go on vacation in July.' },
    { word: 'weather', ru: 'погода', uz: 'ob-havo', definition: 'The state of the atmosphere', example: 'The weather is sunny.' },
    { word: 'healthy', ru: 'здоровый', uz: 'sogʻlom', definition: 'In good health', example: 'A healthy diet is important.' },
    { word: 'exercise', ru: 'упражнение', uz: 'mashq', definition: 'Activity requiring physical effort', example: 'He does exercise daily.' },
    { word: 'museum', ru: 'музей', uz: 'muzey', definition: 'A building where artifacts are displayed', example: 'We visited a museum.' },
    { word: 'library', ru: 'библиотека', uz: 'kutubxona', definition: 'A place with collections of books', example: 'The library is quiet.' },
    { word: 'traffic', ru: 'движение', uz: 'harakat', definition: 'Vehicles moving along public roads', example: 'Traffic is heavy today.' },
    { word: 'expense', ru: 'расход', uz: 'xarajat', definition: 'The cost incurred in or required for something', example: 'Keep your monthly expenses low.' },
    { word: 'repair', ru: 'ремонт', uz: 'taʼmirlash', definition: 'To fix something broken', example: 'They will repair the roof.' },
    { word: 'describe', ru: 'описать', uz: 'tasvirlash', definition: 'Give a detailed account', example: 'Describe your hometown.' },
    { word: 'prefer', ru: 'предпочитать', uz: 'afzal ko‘rmoq', definition: 'Like one thing better than another', example: 'I prefer tea to coffee.' },
    { word: 'borrow', ru: 'занимать', uz: 'qarz olmoq', definition: 'Take and use something of someone else', example: 'May I borrow your pen?' },
    { word: 'return', ru: 'возвращать', uz: 'qaytarmoq', definition: 'Come or go back', example: 'Return the book tomorrow.' },
    { word: 'arrive', ru: 'прибывать', uz: 'kelmoq', definition: 'Reach a place at the end of a journey', example: 'They arrive at noon.' },
    { word: 'depart', ru: 'отправляться', uz: 'joʻnab ketmoq', definition: 'Leave, typically to start a journey', example: 'The bus departs at 9.' },
    { word: 'invite', ru: 'приглашать', uz: 'taklif qilmoq', definition: 'Ask someone to go somewhere', example: 'Invite your friends to dinner.' },
    { word: 'choose', ru: 'выбирать', uz: 'tanlamoq', definition: 'Pick out or select', example: 'Choose the correct answer.' },
    { word: 'explain', ru: 'объяснять', uz: 'tushuntirmoq', definition: 'Make something clear', example: 'Please explain this rule.' },
  ],
  B1: [
    { word: 'confident', ru: 'уверенный', uz: 'ishonchli', definition: 'Feeling or showing confidence', example: 'She is confident about the exam.' },
    { word: 'efficient', ru: 'эффективный', uz: 'samarali', definition: 'Achieving maximum productivity with minimum waste', example: 'An efficient system saves time.' },
    { word: 'responsible', ru: 'ответственный', uz: 'masʼuliyatli', definition: 'Having an obligation to do something', example: 'He is responsible for the report.' },
    { word: 'environment', ru: 'окружающая среда', uz: 'atrof-muhit', definition: 'The natural world', example: 'We must protect the environment.' },
    { word: 'culture', ru: 'культура', uz: 'madaniyat', definition: 'Ideas, customs, and social behavior of people', example: 'They study local culture.' },
    { word: 'achieve', ru: 'достигать', uz: 'erishmoq', definition: 'Successfully bring about a result', example: 'We can achieve our goals.' },
    { word: 'compare', ru: 'сравнивать', uz: 'taqqoslamoq', definition: 'Estimate the similarity or dissimilarity', example: 'Compare the two products.' },
    { word: 'improve', ru: 'улучшать', uz: 'yaxshilamoq', definition: 'Make or become better', example: 'Practice to improve your skills.' },
    { word: 'cancel', ru: 'отменять', uz: 'bekor qilmoq', definition: 'Decide not to proceed', example: 'They canceled the meeting.' },
    { word: 'support', ru: 'поддерживать', uz: 'qoʻllab-quvvatlamoq', definition: 'Bear all or part of the weight; give assistance', example: 'Support your teammates.' },
    { word: 'attention', ru: 'внимание', uz: 'eʼtibor', definition: 'Notice taken of someone or something', example: 'Pay attention to details.' },
    { word: 'opinion', ru: 'мнение', uz: 'fikr', definition: 'A view or judgment', example: 'In my opinion, it is fair.' },
    { word: 'fashion', ru: 'мода', uz: 'moda', definition: 'A popular or the latest style', example: 'Fashion changes quickly.' },
    { word: 'industry', ru: 'промышленность', uz: 'sanoat', definition: 'Economic activity concerned with processing raw materials', example: 'The tech industry is growing.' },
    { word: 'manager', ru: 'менеджер', uz: 'menejer', definition: 'A person responsible for controlling an organization', example: 'Talk to the manager.' },
    { word: 'deliver', ru: 'доставлять', uz: 'yetkazib bermoq', definition: 'Bring and hand over', example: 'They deliver packages daily.' },
    { word: 'complain', ru: 'жаловаться', uz: 'shikoyat qilmoq', definition: 'Express dissatisfaction', example: 'Customers rarely complain.' },
    { word: 'promise', ru: 'обещать', uz: 'vaʼda bermoq', definition: 'Assure someone that one will do something', example: 'I promise to call you.' },
    { word: 'recommend', ru: 'рекомендовать', uz: 'tavsiya qilmoq', definition: 'Put forward with approval', example: 'Can you recommend a book?' },
    { word: 'challenge', ru: 'вызов', uz: 'chaqiriq', definition: 'A call to participate in a contest or to prove something', example: 'This task is a challenge.' },
  ],
  B2: [
    { word: 'consequence', ru: 'последствие', uz: 'oqibat', definition: 'A result or effect', example: 'Consider the consequences of your actions.' },
    { word: 'perspective', ru: 'перспектива', uz: 'nuqtai nazar', definition: 'A particular attitude toward something', example: 'Try a different perspective.' },
    { word: 'maintain', ru: 'поддерживать', uz: 'saqlamoq', definition: 'Cause to continue', example: 'Maintain a healthy lifestyle.' },
    { word: 'justify', ru: 'оправдывать', uz: 'oqloq', definition: 'Show or prove to be right or reasonable', example: 'You must justify your choice.' },
    { word: 'interpret', ru: 'интерпретировать', uz: 'talqin qilmoq', definition: 'Explain the meaning of', example: 'How do you interpret this data?' },
    { word: 'implement', ru: 'внедрять', uz: 'amalga oshirmoq', definition: 'Put into effect', example: 'Implement the new policy.' },
    { word: 'allocate', ru: 'распределять', uz: 'taqsimlamoq', definition: 'Distribute resources for a purpose', example: 'Allocate more time to study.' },
    { word: 'emerge', ru: 'появляться', uz: 'paydo bo‘lmoq', definition: 'Become apparent or prominent', example: 'New problems emerged.' },
    { word: 'decline', ru: 'снижение', uz: 'pasayish', definition: 'Become smaller, fewer, or less', example: 'A decline in sales was reported.' },
    { word: 'sustain', ru: 'поддерживать', uz: 'qoʻllab-quvvatlamoq', definition: 'Strengthen or support physically or mentally', example: 'Sustain effort over time.' },
    { word: 'assess', ru: 'оценивать', uz: 'baholamoq', definition: 'Evaluate or estimate', example: 'Assess the risks first.' },
    { word: 'hypothesis', ru: 'гипотеза', uz: 'taxmin', definition: 'A supposition made on limited evidence', example: 'Test the hypothesis.' },
    { word: 'relevant', ru: 'уместный', uz: 'dolzarb', definition: 'Closely connected or appropriate', example: 'Provide relevant examples.' },
    { word: 'capability', ru: 'возможность', uz: 'qobiliyat', definition: 'The power or ability to do something', example: 'The device has multiple capabilities.' },
    { word: 'conflict', ru: 'конфликт', uz: 'mojaro', definition: 'A serious disagreement or argument', example: 'They resolved the conflict.' },
    { word: 'strategy', ru: 'стратегия', uz: 'strategiya', definition: 'A plan of action', example: 'We need a clear strategy.' },
    { word: 'analysis', ru: 'анализ', uz: 'tahlil', definition: 'Detailed examination of the elements', example: 'Their analysis was thorough.' },
    { word: 'component', ru: 'компонент', uz: 'komponent', definition: 'A part or element of a larger whole', example: 'Replace the faulty component.' },
    { word: 'compromise', ru: 'компромисс', uz: 'murosa', definition: 'An agreement reached by each side making concessions', example: 'They found a compromise.' },
  ],
  C1: [
    { word: 'coherent', ru: 'согласованный', uz: 'mantiqli', definition: 'Logical and consistent', example: 'Present a coherent argument.' },
    { word: 'ambiguous', ru: 'двусмысленный', uz: 'noaniq', definition: 'Open to more than one interpretation', example: 'The sentence is ambiguous.' },
    { word: 'meticulous', ru: 'тщательный', uz: 'sinchkov', definition: 'Showing great attention to detail', example: 'Be meticulous with citations.' },
    { word: 'inevitable', ru: 'неизбежный', uz: 'muqarrar', definition: 'Certain to happen', example: 'Change is inevitable.' },
    { word: 'notwithstanding', ru: 'несмотря на', uz: 'qaramay', definition: 'In spite of', example: 'Notwithstanding the delay, we finished.' },
    { word: 'scrutiny', ru: 'внимательное изучение', uz: 'sinchkov tekshiruv', definition: 'Critical observation or examination', example: 'Under media scrutiny.' },
    { word: 'discrepancy', ru: 'расхождение', uz: 'ziddiyat', definition: 'A lack of similarity', example: 'A discrepancy in the results.' },
    { word: 'paradigm', ru: 'парадигма', uz: 'paradigma', definition: 'A typical example or pattern', example: 'A new scientific paradigm.' },
    { word: 'precipitate', ru: 'ускорять', uz: 'tezlashtirmoq', definition: 'Cause an event to happen suddenly', example: 'Precipitate a crisis.' },
    { word: 'ubiquitous', ru: 'повсеместный', uz: 'har yerda uchraydigan', definition: 'Present, appearing, or found everywhere', example: 'Smartphones are ubiquitous.' },
    { word: 'conundrum', ru: 'головоломка', uz: 'murakkab muammo', definition: 'A confusing and difficult problem', example: 'A moral conundrum.' },
    { word: 'detrimental', ru: 'вредный', uz: 'zararli', definition: 'Tending to cause harm', example: 'Detrimental effects on health.' },
    { word: 'epitome', ru: 'воплощение', uz: 'eng yorqin namuna', definition: 'A perfect example', example: 'The epitome of elegance.' },
    { word: 'facet', ru: 'аспект', uz: 'jomila/yoqlama', definition: 'A particular aspect or feature', example: 'Every facet of life.' },
    { word: 'inadvertent', ru: 'непреднамеренный', uz: 'bexosdan', definition: 'Not resulting from deliberate planning', example: 'An inadvertent error.' },
    { word: 'lucid', ru: 'ясный', uz: 'aniq', definition: 'Expressed clearly', example: 'A lucid explanation.' },
    { word: 'resilient', ru: 'устойчивый', uz: 'moslashuvchan', definition: 'Able to recover quickly', example: 'A resilient community.' },
    { word: 'substantiate', ru: 'подтверждать', uz: 'asoslamoq', definition: 'Provide evidence to support', example: 'Substantiate your claims.' },
    { word: 'transient', ru: 'временный', uz: 'vaqtinchalik', definition: 'Lasting only for a short time', example: 'A transient trend.' },
  ],
  C2: [
    { word: 'obfuscate', ru: 'затемнять', uz: 'noaniq qilmoq', definition: 'Render obscure or unintelligible', example: 'Obfuscate the true meaning.' },
    { word: 'recalcitrant', ru: 'непокорный', uz: 'itoatsiz', definition: 'Having an obstinately uncooperative attitude', example: 'A recalcitrant child.' },
    { word: 'pulchritude', ru: 'красота', uz: 'goʻzallik', definition: 'Beauty', example: 'Pulchritude of the landscape.' },
    { word: 'incongruous', ru: 'несоответствующий', uz: 'mos kelmaydigan', definition: 'Not in harmony with the surroundings', example: 'Incongruous elements in the design.' },
    { word: 'nonchalant', ru: 'беззаботный', uz: 'xotirjam', definition: 'Feeling casually calm and relaxed', example: 'A nonchalant smile.' },
    { word: 'munificent', ru: 'щедрый', uz: 'saxiy', definition: 'Larger or more generous than usual', example: 'A munificent donation.' },
    { word: 'apocryphal', ru: 'апокрифический', uz: 'shubhali', definition: 'Of doubtful authenticity', example: 'An apocryphal story.' },
    { word: 'antediluvian', ru: 'допотопный', uz: 'qadimiy', definition: 'Ridiculously old-fashioned', example: 'Antediluvian beliefs.' },
    { word: 'perspicacious', ru: 'проницательный', uz: 'farosatli', definition: 'Having a ready insight', example: 'A perspicacious critic.' },
    { word: 'sesquipedalian', ru: 'высокопарный', uz: 'balandparvoz', definition: 'Characterized by long words', example: 'Sesquipedalian prose.' },
    { word: 'abstruse', ru: 'трудный для понимания', uz: 'qiyin tushunarli', definition: 'Difficult to understand', example: 'An abstruse theory.' },
    { word: 'pellucid', ru: 'прозрачный', uz: 'shaffof', definition: 'Translucently clear', example: 'Pellucid water.' },
    { word: 'equanimity', ru: 'хладнокровие', uz: 'bosiqlik', definition: 'Mental calmness', example: 'Maintain equanimity under pressure.' },
    { word: 'assiduous', ru: 'усердный', uz: 'tirishqoq', definition: 'Showing great care and perseverance', example: 'An assiduous researcher.' },
    { word: 'excoriate', ru: 'резко критиковать', uz: 'qattiq tanqid qilmoq', definition: 'Censure or criticize severely', example: 'Excoriate the policy.' },
    { word: 'impecunious', ru: 'неимущий', uz: 'kambagʻal', definition: 'Having little or no money', example: 'Impecunious students.' },
    { word: 'insouciant', ru: 'беззаботный', uz: 'befarq', definition: 'Showing a casual lack of concern', example: 'An insouciant attitude.' },
    { word: 'recondite', ru: 'малопонятный', uz: 'murakkab', definition: 'Little known; abstruse', example: 'Recondite facts.' },
    { word: 'trenchant', ru: 'резкий', uz: 'keskin', definition: 'Vigorous or incisive in expression', example: 'Trenchant criticism.' },
  ],
};
